TB-528. Loading command added + docs.
Q-CIS-DEV/trood-cli pull request #3
Opened 2020-08-14 11:44 UTC by sobrabd

2020-09-07 09:29 UTC, orn0t requested changes

2020-09-07 09:29 UTC, orn0t commented on trood/cli/spaces.py
> +@click.option('-t', '--token')
token уже вынесен в глобальные аргументы, зачем его еще раз делать? можно просто взять через get_token

2020-09-07 09:29 UTC, orn0t commented on trood/cli/spaces.py
> +@click.option('-t', '--token')
--verbose тоже бы перенести в глобальные аргументы, для других команд тоже пригодиться

2020-09-15 11:41 UTC, orn0t requested changes

2020-09-15 11:41 UTC, orn0t commented on trood/cli/spaces.py
> +        headers={"Authorization": f"{token.replace(':', '')}"}
А зачем там двоеточие вообще? почему его надо ставить а потом убирать?

2020-09-24 12:32 UTC, sobrabd commented on trood/cli/spaces.py
> +        headers={"Authorization": f"{token.replace(':', '')}"}
Ну у нас походу не очень одинаково везде обрабатывается token
Как правло токен используется с двоеточием
https://github.com/Q-CIS-DEV/trood-cli/blob/master/trood/cli/utils.py#L13
https://github.com/Q-CIS-DEV/trood-cli/search?q=get_token

кроме этого эндпоинта
https://github.com/Q-CIS-DEV/trood-auth/blob/dev/t_auth/core/authentication.py#L24
а тут нужно передавать токен без двоеточий
Походу нужно синхронизировать все эндпоинты, чтобы токен выглядел всегда одинакого

2020-11-13 09:36 UTC, sobrabd commented on trood/cli/spaces.py
> +        headers={"Authorization": f"{token.replace(':', '')}"}
Короче там изначально в cli был токен такого вида Token: <token> это работало много где, но не работало в login/trood
по идеи токен должен быть без двоеточия, поэтому его сейчас убрал.

2020-11-13 09:38 UTC, sobrabd commented on trood/cli/spaces.py
> +    time.sleep(1)
добавил слип, так как без него первый запрос не успевает отработать

2020-11-17 07:35 UTC, kirpastuhov approved these changes

2020-11-20 14:51 UTC, merged