TB-613. Add alias support to cli
Q-CIS-DEV/trood-cli pull request #7
Opened 2020-11-09 14:16 UTC by kirpastuhov

2020-11-10 10:17 UTC, sobrabd commented on trood/cli/spaces.py
> +        get_em_ulr(f'api/v1.0/spaces/{space_id if space_id else space_alias}/'),
если space_id не нашелся то тут все сломается, будет NameError по идеи
тоже для app_id

2020-11-11 08:27 UTC, orn0t requested changes

2020-11-11 08:27 UTC, orn0t commented on trood/cli/spaces.py
> +    for space in spaces:
Фильтруй сразу нужный

2020-11-11 08:27 UTC, orn0t commented on trood/cli/spaces.py
> +    for app in apps:
тоже самое, фильтруй сразу нужный через rql

2020-11-12 09:56 UTC, merged